# Generated by Django 3.0.8 on 2020-07-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_userfeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeed',
            old_name='user_profile',
            new_name='user',
        ),
    ]
