# Generated by Django 3.0.8 on 2020-07-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20200718_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
